
[general]
# execute every benchmark multiple times TODO: is it neccessary?
iterations=2
# generete output to
output_dir="benchmark-output"
# override outpu_dir or create unique output dir
override_output=false

log_file="benchmark.log"

# input from custom TPTP files
# comment whole [[input]] to disable
[[input]]
[input.TPTP]
# where to find TPTP files
path=""

[[input.TPTP.files]]
# wildcards supported ?
path="lib/TPTP/*/CNF*.p"
# optional comment will be written to output file
comment="cnf tests"

[[input.TPTP.files]]
path="lib/TPTP"
comment=""

# input from Logic Formula Generator https://github.com/Mateusz-Grzelinski/lfg
# comment whole [[input]] to disable
[[input]]
[input.LFG]
# look for executable in PATH
executable="lfg"
# append to path env variable, comment or leave empty to disable
PATH=["lib/lfg/bin"]

[[testSuite]]
name="prover9 test"

# name available in PATH
executable="prover9"

# append to path env variable, comment or leave empty to disable
PATH=["lib/prover9"]

# metadata appended to each file, comment to disable
version_options="--version"
comment=""

# options always appended to executable, comment or leave empty to disable
options=["--quiet"]

[testSuite.output]
# program print everything to stdout
stdout=true
# program prints output with command line option
output_option="-o"
# program print everything to stderr
stderr=true
# program specifies
err_option="-e"

# specify command line options to test
[[testSuite.testCase]]
name="Prover9 without options"
# mutually exclusive options input_as_stdin, input_as_last_argument, input_after_option
input_as_stdin=true
# input_as_last_argument=false
# input_after_option="-o"

# nested [] in options means 'pick one of listed'. Remember toml arrays can hold only one type.
options=[]

[[testSuite.testCase]]
input_as_stdin=true
# input_as_last_argument=false
# input_after_option=""
name="Prover9 with -Auto2"
options=["-Auto2"]
