[general]
# generate output to
output_dir="benchmark-output"
log_file="benchmark.log"

[[translators]]
from_format="TPTP"
to_format="LADR"
PATH="../provers/LADR-2009-11A/bin"
executable="tptp_to_ladr"
options=[]
input_after_option="-TPTP"
input_as_last_argument=false
output_after_option=""

[[testInputs]]
# for specifying include/exclude in testCase
name="variableLength"
# path to files
path="."
# wildcards supported
files=["**/*.p"]
# currently only TPTP
format="TPTP"

[[testSuites]]
name="ls dummy test"
# name available in PATH
executable="ls"
# append to path env variable, comment or leave empty to disable
#PATH="../provers/LADR-2009-11A/bin"
#PATH="lib/prover9"
# metadata appended to each file, comment to disable
version="0.1"
# options always appended to executable, comment or leave empty to disable
options=["-1"]
# specify command line options to test

[[testSuites.testCases]]
# metadata
name="ls witout options"
# what file format is accepted by prover, input will be automatically translated if possible
format="LADR"
# mutually exclusive options input_as_last_argument, input_after_option
#input_as_last_argument=true
#input_after_option="-o"

# mutually exclusive: include or exclude inputs for test. Comment both to test all
include_only=["variableLength"]
#exclude=[""]

# list of options to test,
# set to [] or add empty string as option to run testcase without options
options=[]

[[testSuites.testCases]]
name="ls -Auto2"
format="LADR"
options=["-a", "-l"]
