
@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package Generators {
  note "Every generator \ncan be used by CNFFormulaGenerator" as N
 }

Generators -* CNFFormulaGenerator
CNFFormulaGenerator *-- ConstraintSolver
CNFFormulaGenerator - CNFFormula

class CNFFormulaGenerator {
  variable_names 
  functor_names 
  functor_arity 
  functor_recursion_depth 
  predicate_names
  predicate_arities
  atom_connectives
  **clause_lengths **
  **number_of_literals**
  **number_of_clauses**
}

class ConstraintSolver {
  allowed_clause_lengths
  number_of_literals
  number_of_clauses
  + solve()
}

@enduml
