@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package SyntaxTree {
  /' AstElement <|-- FolElement '/
  FolElement <|-- CNFFormula
  FolElement <|-- CNFClause
  FolElement <|-- Literal
  FolElement <|-- Atom
  FolElement <|-- Predicate
  FolElement <|-- Term
  Term <|-- Functor
  Term o-- Functor
  Term <|-- Variable
}

CNFFormula o- CNFClause
CNFClause o- Literal
Literal o- Atom
Atom o- Predicate
Atom o- Term
Predicate o-- Term

abstract class FolElement {
  + accept(visitor)
  ..
}

class CNFFormula {
	cnf/1
	cnf/2
	..
}

class CNFClause {
	cnf(literal | literal).
	..
}

class Literal {
	atom, ~atom
	..
}

class Atom {
	p, V = V, f != V
	..
}

class Predicate {
	p, p(f), p(V, f)
	..
}

abstract class Term {
}

class Functor {
	f, f(f), f(V), f(f(f))
	..
}

class Variable {
	V1, V2
	..
}
@enduml
