@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package ExportUtils {
  Exporter <|-- TPTPExporter
  Exporter - CNFFormulaVisitor
  TPTPExporter *-- TPTPHeader
  CNFFormulaVisitor --o CNFFormulaInfo
}

CNFFormula ()-- Exporter

class CNFFormulaVisitor {
  + visit_variable(variable)
  + visit_functor(functor)
  + visit_predicate(predicate)
  + visit_atom(atom)
  + visit_literal(literal)
  + visit_cnf_clause(CNFClause)
  + visit_cnf_formula(CNFFormula)
}

class CNFFormulaInfo {
  number_of_{variables,functors,predicates,...}
  number_of_horn_clauses_instances
  number_of_constant_functors
}

abstract class Exporter {
+ export(expression: CNFFormula, filename: str) 
}

class TPTPExporter {
}

class TPTPHeader {
  cnf_formula_info
}

@enduml
