@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package SignatureGenerators {

CNFFormulaSignatureGenerator o-- CNFClauseSignatureGenerator
CNFClauseSignatureGenerator o-- LiteralSignaturegnerator
LiteralSignaturegnerator o-- AtomSignatureGenerator
AtomSignatureGenerator o-- PredicateSignaturegenerator
AtomSignatureGenerator o-- VariableGenerator
PredicateSignaturegenerator o-- VariableGenerator
PredicateSignaturegenerator o-- FunctorSignatureGenerator
VariableGenerator -o FunctorSignatureGenerator 
}

class CNFFormulaSignatureGenerator {
	cnf/1
	cnf/2
	..
}

class CNFClauseSignatureGenerator {
	cnf(literal | literal).
	..
}

class LiteralSignaturegnerator {
	atom, ~atom
	..
}

class AtomSignatureGenerator {
	p, V = V, f != V
	..
}

class PredicateSignaturegenerator {
	p, p(f), p(V, f)
	..
}

class FunctorSignatureGenerator {
	f, f(f), f(V), f(f(f))
	..
}

class VariableGenerator {
	V1, V2
	..
}
@enduml
