@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package ExportUtils {
  Exporter <|-- TPTPExporter
  Exporter - CNFFormulaVisitor
  TPTPExporter *-- TPTPHeader
  CNFFormulaVisitor -* MathSense
  CNFFormulaVisitor --* CNFFormulaInfo
}

CNFFormula ()-- Exporter

class MathSense {
  + hash_variable(scope: Optional[CNFClause], variable: Variable) -> int:
  + hash_functor(functor: Functor) -> int:
  + hash_predicate(predicate: Predicate) -> int:
  + hash_atom(scope: Optional[CNFClause], atom: Atom) -> int:
  + hash_literal(scope: Optional[CNFClause], literal: Literal) -> int:
  + hash_clause(clause: CNFClause) -> int:
}

class CNFFormulaVisitor {
  + visit_variable(variable):
  + visit_functor(functor):
  + visit_predicate(predicate):
  + visit_atom(atom):
  + visit_literal(literal):
  + visit_cnf_clause(CNFClause):
  + visit_cnf_formula(CNFFormula):
}

class CNFFormulaInfo {
  number_of
  number_of_instances
  clause_lengths
  number_of_horn_clauses_instances
  predicate_arities
}

abstract class Exporter {
+ export(expression: CNFFormula, filename: str) 
}

class TPTPExporter {
}

class TPTPHeader {
  cnf_formula_info
}

@enduml
