@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

/' AstElement <|-- FolElement '/

CNFFormula o-- CNFClause
CNFClause o-- Literal
Literal o-- Atom
Atom o-- Predicate
Predicate o-- Variable
Predicate o-- Functor
Functor o-- Variable

class CNFFormula {
	cnf/1 & cnf/2
	..
}

class CNFClause {
	cnf(literal | literal).
	..
}

class Literal {
	atom, ~atom
	..
}

class Atom {
	p, p = p, p != V
	..
}

class Predicate {
	p, p(f), p(V, f)
	..
}

class Functor {
	f, f(f), f(V), f(f(f))
	..
}

class Variable {
	V1, V2
	..
}
@enduml
