@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package Generators {
  Predicategenerator <-- SafetyLivenessPredicateGenerator
}

Generators -* CNFSafetyLivenessGenerator
CNFSafetyLivenessGenerator *-- ConstraintSolver
CNFSafetyLivenessGenerator -> CNFFormula
CNFFormula <- Exporter
Exporter <|-- TPTPExporter

class CNFSafetyLivenessGenerator {
  variable_names 
  functor_names 
  functor_arity 
  functor_recursion_depth 
  predicate_names
  predicate_arities
  atom_connectives
  clause_lengths 
  **number_of_literals**
  **number_of_clauses**
}

class ConstraintSolver {
  number_of_literals
  number_of_clauses
}

abstract class Exporter {
}

class SafetyLivenessPredicateGenerator {
	p, p(f), p(f, f), p(V, V)
	..
}

class Predicategenerator {
	p, p(f), p(V, f)
	..
}

@enduml
