@startuml

package "CNF generator" {
VariableGenerator o- ClauseGenerator
VariableGenerator -- Variable
ClauseGenerator -- Clause
Variable o- Clause
}

class VariableGenerator {
		+ name: str
		+ unique_variables: int = 100
		+ total_variables: int = 2_000_000
		+ negate_probability: float = 0.5
		- __variable_number: int = 0
		- __generated_used_variables: int = 0
		+ variables_left() : int
		+ get_random_variable() : Variable
		+ get_new_variable() : Variable
		+ get_used_variable() : Variable
}

class ClauseGenerator {
		+ variable_gen: VariableGenerator
		+ max_clause_size: int = None
		+ total_clauses: int = 200
		- __generated_clauses: int = 0
		+ clauses_left() : int
		+ get_new_clause() : Clause
}

class Variable {
		+ name: str
		+ number: int = 0
		+ negated: bool = False
		+ as_dimacs() : string
}

class Clause {
		+ variables: [Variable]
		+ as_dimacs() : string
}

@enduml
