@startuml
skinparam dpi 300

skinparam class {
  backgroundColor Ivory
  borderColor DarkRed
}

package Generator {
  package GeneratorPresets {
    RandomCNFFormulaGenerator *-- CNFConstraintSolver
    CNFConstraintSolver <|-- Z3CNFConstraintSolver
  }
  package SubGenerators {
    note "Every sub-generator \ncan be used by RandomCNFFormulaGenerator" as N
  }
  GeneratorPresets -- SubGenerators 
}
RandomCNFFormulaGenerator -() CNFFormula
InputParams ()-- RandomCNFFormulaGenerator

class RandomCNFFormulaGenerator {
  variable_names 
  functor_names 
  functor_arity 
  functor_recursion_depth 
  predicate_names
  predicate_arities
  atom_connectives
  **clause_lengths **
  **number_of_literals**
  **number_of_clauses**
}

class CNFConstraintSolver {
  allowed_clause_lengths
  number_of_literals
  number_of_clauses
  + solve()
}

class Z3CNFConstraintSolver {
  - _solve()
  + solve()
}
@enduml
